INSERT INTO realisateur (id_real, prenom, nom) VALUES (18, 'Cédric','Klapisch');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (7, 'Terry','Gilliam');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (5, 'James','Cameron');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (6, 'Peter','Weir');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (11, 'Ridley','Scott');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (12, 'Jean','Becker');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (13, 'Danny','Boyle');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (14, 'Sergio','Leone');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (8, 'John','Hillcoat');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (9, 'Alejandro','González Iñárritu');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (15, 'Steven','Spielberg');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (1, 'M. Night','Shyamalan');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (2, 'Juan Carlos','Fresnadillo');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (3, 'Chan-wook','Park');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (4, 'Joël','Coen');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (40, 'Ethan','Coen');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (16, 'Paul','Thomas Anderson');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (17, 'Sean','Penn');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (19, 'Michel','Hazanavicius');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (20, 'Jean-Marie','Poiré');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (21, 'Roberto','Benigni');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (22, 'George','Lucas');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (23, 'Robert','Zemeckis');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (24, 'Francis Ford','Coppola');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (25, 'Charles','Chaplin');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (26, 'Peter','Jackson');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (27, 'Hayao','Miyazaki');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (28, 'Byron','Haskin');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (29, 'Franck','Capra');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (10, 'Bernard','Campan');
INSERT INTO realisateur (id_real, prenom, nom) VALUES (100, 'Didier','Bourdon');
